set_property SRC_FILE_INFO {cfile:/home/ahmet/Desktop/photonic-inference-lab/fpga/led_blink_z010/led_blink_z010.srcs/constrs_1/new/led_blink.xdc rfile:../../../led_blink_z010.srcs/constrs_1/new/led_blink.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports { clk }]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R14   IOSTANDARD LVCMOS33 } [get_ports { led }]
